// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjCshU2JBYt9hcxiigD-HQ5NHMeV6Fmnw',
    appId: '1:149741662864:web:d23d8fb71f0177b32f5e15',
    messagingSenderId: '149741662864',
    projectId: 'binurimovies',
    authDomain: 'binurimovies.firebaseapp.com',
    storageBucket: 'binurimovies.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ng1L7sa9Ch_2BJ7HLdy5aFyfCqjOhFw',
    appId: '1:149741662864:android:f757af0b2a4910022f5e15',
    messagingSenderId: '149741662864',
    projectId: 'binurimovies',
    storageBucket: 'binurimovies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcL9bUz7Rv3NoXc9JD2isFrrer_Xvm_PA',
    appId: '1:149741662864:ios:b22c2e5bc4ddb73d2f5e15',
    messagingSenderId: '149741662864',
    projectId: 'binurimovies',
    storageBucket: 'binurimovies.appspot.com',
    iosBundleId: 'com.example.movieAppExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcL9bUz7Rv3NoXc9JD2isFrrer_Xvm_PA',
    appId: '1:149741662864:ios:e57ffa146f11a47b2f5e15',
    messagingSenderId: '149741662864',
    projectId: 'binurimovies',
    storageBucket: 'binurimovies.appspot.com',
    iosBundleId: 'com.example.movieAppExample.RunnerTests',
  );
}
